language: cpp

matrix:
  include:
    - os: linux
      dist: xenial
      compiler: gcc-8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - libboost-test-dev
            - libsdl2-dev
      env:
        - CC=gcc-8
        - CXX=g++-8
        - AR=gcc-ar-8

    - os: osx
      osx_image: xcode10.1
      addons:
        homebrew:
          packages:
          - sdl2

before_install:
  - eval "${MATRIX_EVAL}"
script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - make test
